EXEC sys.sp_configure N'show advanced options', N'1'  RECONFIGURE WITH OVERRIDE
GO
EXEC sys.sp_configure N'cost threshold for parallelism', N'5'
GO
RECONFIGURE WITH OVERRIDE
GO
EXEC sys.sp_configure N'show advanced options', N'0'  RECONFIGURE WITH OVERRIDE
GO

CREATE DATABASE DEMO_PARALELISMO
GO
USE DEMO_PARALELISMO
GO

SET NOCOUNT ON

CREATE TABLE CLIENTE
(
	ID_CLIENTE INT IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(100)
)
GO

INSERT INTO CLIENTE (NOME) VALUES ('MARCIO'),('REGINALDO'),('LEONARDO')


CREATE TABLE PEDIDO 
(
	ID_PEDIDO INT IDENTITY(1,1) PRIMARY KEY,
	ID_CLIENTE INT,
	COL1 VARCHAR(MAX),
	COL2 VARCHAR(MAX),
	COL3 VARCHAR(MAX),
	DT_CADASTRO DATETIME DEFAULT GETDATE()
)


INSERT INTO PEDIDO (ID_CLIENTE,COL1,COL2,COL3)
VALUES (1,NEWID(),NEWID(),NEWID()),
       (2,NEWID(),NEWID(),NEWID()),
       (2,NEWID(),NEWID(),NEWID()),
       (3,NEWID(),NEWID(),NEWID()),
       (3,NEWID(),NEWID(),NEWID()),
       (3,NEWID(),NEWID(),NEWID())
GO

INSERT INTO PEDIDO WITH (TABLOCK)
(ID_CLIENTE,COL1,COL2,COL3,DT_CADASTRO) 
SELECT
	ID_CLIENTE,
	COL1,
	COL2,
	COL3,
	DT_CADASTRO
FROM
	PEDIDO
GO 19

------- FUNCAO PARA DEMO.
CREATE FUNCTION fn_formata_data
(
	@PARAMETRO DATETIME
)
RETURNS VARCHAR(10)
AS
BEGIN
	-- Declare the return variable here
	DECLARE @RESULT DATETIME

	-- Add the T-SQL statements to compute the return value here
	SELECT @RESULT = CONVERT(VARCHAR(10),@PARAMETRO,103) + ' ' + CONVERT(VARCHAR(5),@PARAMETRO,108)

	-- Return the result of the function
	RETURN @RESULT

END
GO

-------- ADICIONANDO COLUNA COMPUTADA UTILIZANDO UMA FUNCAO UDF.
ALTER TABLE PEDIDO ADD DATA_FORMATADA AS dbo.fn_formata_data(DT_CADASTRO)